apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80  

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: maxtonk/eschool:front
          ports:
            - containerPort: 80
              protocol: TCP
          env:
          - name: baseURL
            value: backend-service
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "50m"
